### ISSUE TITLE
PhpStorm 9 support (jump to model does not work)

### ISSUE THREAD

**Issue by igordegraf** [topdown/phpStorm-CC-Helpers#9]
In phpstorm 9 jumping to model (CTRL+click) from controller opens helper file included to project from this solution instead of real model file.
Autocomplete works fine.

Do anyone knows workaround or solution (fix) ?

**Comment by topdown** [comment]
I have not messed with CI in a long time. Feel free to make a pull request if you find a solution.

**Comment by bytecode12** [comment]
Hey igordegraf, have made change in original Ci_phpStrom.php or my_models.php file ?
i made change as per my convenient  and its works fine for me :) .....

**Comment by jthanto** [comment]
I'm having this problem as well, did anyone have a solution for this?

**Comment by topdown** [comment]
I just merged in 2 PR's
Pull the latest and see if it fixes it for you.

**Comment by jthanto** [comment]
I'll check this out first thing at work tomorrow =]

**Comment by jthanto** [comment]
I just pulled the latest updates, and it is still the same behavior. It works for model->function, but not the actual models. Also autocomplete still works.
I might try to look into this some day, got no experience with this kind of things though.

**Comment by topdown** [comment]
What version CI are you using?

**Comment by jthanto** [comment]
Sorry for the all to delayed answer (life suddenly got real), and that i havn't even checked what versions of phpstorm that are supported (ther's not really any excuse). 
I use PhpStorm 2016.2.2
Build #PS-162.2380.11, built on October 24, 2016

**Comment by jthanto** [comment]
Sorry for the delayed answer (life suddenly got real), and that i havn't checked what versions of CI that are supported (there's not really any excuse, and i will double check this now). I use CI 3.1.0 :)
